on:
  workflow_dispatch:

name: API Call

jobs:
  run-r-script:
    runs-on: ubuntu-latest
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        R_KEEP_PKG_SOURCE: yes
        MY_SECRET: ${{ secrets.my_secret }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: run-script
        run: Rscript R/test.R
