on:
  workflow_dispatch:

name: API Call

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
    # the next 3 lines setup the keyring approach to store the API key
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      MY_SECRET: ${{ secrets.my_secret }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::httr
            any::keyring
            any::jsonlite
            any::tidyverse

      - name: run-script
        run: Rscript R/test.R

      - name: run-script
        run: Rscript R/call_api.R

      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com
          git add -A
          git commit -m "Fetched AQI csv" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
