on:
  workflow_dispatch:

name: API Call

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: run-script
        run: Rscript R/test.R
