# This workflow is triggered manually or on a schedule to make an API call
# and commit the results to the repository.

on:
  workflow_dispatch: # Triggered manually for testing

  schedule: # Triggered on a schedule
    - cron: "15 0-23 * * *" # every hour at 15 minutes past the hour

name: API Call

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} # GitHub Personal Access Token
      R_KEEP_PKG_SOURCE: yes
      DATA_GOV_API_KEY: ${{ secrets.DATA_GOV_API_KEY }} # API key for the data.gov API

    steps:
      - uses: actions/checkout@v3 # Checks out the repository

      - uses: r-lib/actions/setup-r@v2 # Sets up R environment
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2 # Sets up R dependencies
        with:
          cache-version: 2
          packages: any::httr
            any::jsonlite
            any::tidyverse

      - name: run-script # Runs the test.R script
        run: Rscript R/test.R

      - name: run-script # Runs the call_api.R script
        run: Rscript R/call_api.R

      - name: commit files # Commits the changes to the repository
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Results from GHA" || echo "no changes to commit"
          git push origin || echo "no changes to commit"-
